// Generated by scripts/gen-db-types.mjs — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      batches: {
        Row: {
          id: number
          code: string
          start_date: string
          close_date: string | null
          status: string | null
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          code: string
          start_date: string
          close_date?: string | null
          status?: never
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          code?: string
          start_date?: string
          close_date?: string | null
          status?: never
          note?: string | null
          created_at?: string
        }
        Relationships: []
      }
      buyers: {
        Row: {
          id: number
          code: string
          name: string
          company: string | null
          phone: string | null
          is_active: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          code: string
          name: string
          company?: string | null
          phone?: string | null
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          code?: string
          name?: string
          company?: string | null
          phone?: string | null
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: []
      }
      chick_purchases: {
        Row: {
          id: number
          date: string
          batch_id: number
          supplier_id: number
          chicks_placed: number
          rate: number
          discount: number
          total_price: number | null
          net_price: number | null
          is_void: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          date: string
          batch_id: number
          supplier_id: number
          chicks_placed: number
          rate: number
          discount?: number
          total_price?: never
          net_price?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          date?: string
          batch_id?: number
          supplier_id?: number
          chicks_placed?: number
          rate?: number
          discount?: number
          total_price?: never
          net_price?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "chick_purchases_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chick_purchases_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      items: {
        Row: {
          id: number
          code: string
          name: string
          category: Database["public"]["Enums"]["item_category"]
          unit: string
          unit_weight_kg: number | null
          is_active: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          code: string
          name: string
          category: Database["public"]["Enums"]["item_category"]
          unit: string
          unit_weight_kg?: number | null
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          code?: string
          name?: string
          category?: Database["public"]["Enums"]["item_category"]
          unit?: string
          unit_weight_kg?: number | null
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: []
      }
      mortalities: {
        Row: {
          id: number
          date: string
          batch_id: number
          shed_id: number
          dead_count: number
          reason: Database["public"]["Enums"]["mortality_reason"]
          is_void: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          date: string
          batch_id: number
          shed_id: number
          dead_count: number
          reason?: Database["public"]["Enums"]["mortality_reason"]
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          date?: string
          batch_id?: number
          shed_id?: number
          dead_count?: number
          reason?: Database["public"]["Enums"]["mortality_reason"]
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "mortalities_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "mortalities_shed_id_fkey"
            columns: ["shed_id"]
            isOneToOne: false
            referencedRelation: "sheds"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          id: number
          date: string
          party: Database["public"]["Enums"]["party_type"]
          chick_purchase_id: number | null
          purchase_id: number | null
          sale_id: number | null
          amount: number
          method: Database["public"]["Enums"]["payment_method"]
          is_void: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          date: string
          party: Database["public"]["Enums"]["party_type"]
          chick_purchase_id?: number | null
          purchase_id?: number | null
          sale_id?: number | null
          amount: number
          method?: Database["public"]["Enums"]["payment_method"]
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          date?: string
          party?: Database["public"]["Enums"]["party_type"]
          chick_purchase_id?: number | null
          purchase_id?: number | null
          sale_id?: number | null
          amount?: number
          method?: Database["public"]["Enums"]["payment_method"]
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payments_chick_purchase_id_fkey"
            columns: ["chick_purchase_id"]
            isOneToOne: false
            referencedRelation: "chick_purchases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_purchase_id_fkey"
            columns: ["purchase_id"]
            isOneToOne: false
            referencedRelation: "purchases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_sale_id_fkey"
            columns: ["sale_id"]
            isOneToOne: false
            referencedRelation: "sales"
            referencedColumns: ["id"]
          },
        ]
      }
      purchases: {
        Row: {
          id: number
          date: string
          item_id: number
          supplier_id: number
          qty: number
          unit_price: number
          amount: number | null
          is_void: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          date: string
          item_id: number
          supplier_id: number
          qty: number
          unit_price: number
          amount?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          date?: string
          item_id?: number
          supplier_id?: number
          qty?: number
          unit_price?: number
          amount?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchases_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchases_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
        ]
      }
      sales: {
        Row: {
          id: number
          date: string
          batch_id: number
          buyer_id: number
          male_count: number
          female_count: number
          grade: Database["public"]["Enums"]["sale_grade"]
          gross_weight_kg: number
          deduction_per_crate_g: number
          rate: number
          discount: number
          total_birds: number | null
          crates: number | null
          deduction_kg: number | null
          net_weight_kg: number | null
          amount: number | null
          is_void: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          date: string
          batch_id: number
          buyer_id: number
          male_count?: number
          female_count?: number
          grade: Database["public"]["Enums"]["sale_grade"]
          gross_weight_kg: number
          deduction_per_crate_g?: number
          rate: number
          discount?: number
          total_birds?: never
          crates?: never
          deduction_kg?: never
          net_weight_kg?: never
          amount?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          date?: string
          batch_id?: number
          buyer_id?: number
          male_count?: number
          female_count?: number
          grade?: Database["public"]["Enums"]["sale_grade"]
          gross_weight_kg?: number
          deduction_per_crate_g?: number
          rate?: number
          discount?: number
          total_birds?: never
          crates?: never
          deduction_kg?: never
          net_weight_kg?: never
          amount?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "buyers"
            referencedColumns: ["id"]
          },
        ]
      }
      sheds: {
        Row: {
          id: number
          code: string
          name: string
          type: Database["public"]["Enums"]["shed_type"]
          is_active: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          code: string
          name: string
          type: Database["public"]["Enums"]["shed_type"]
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          code?: string
          name?: string
          type?: Database["public"]["Enums"]["shed_type"]
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: []
      }
      suppliers: {
        Row: {
          id: number
          code: string
          name: string
          company: string | null
          phone: string | null
          is_active: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          code: string
          name: string
          company?: string | null
          phone?: string | null
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          code?: string
          name?: string
          company?: string | null
          phone?: string | null
          is_active?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: []
      }
      usages: {
        Row: {
          id: number
          date: string
          batch_id: number
          item_id: number
          kind: Database["public"]["Enums"]["usage_kind"]
          qty: number
          unit_cost: number
          signed_qty: number | null
          cost: number | null
          is_void: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          date: string
          batch_id: number
          item_id: number
          kind?: Database["public"]["Enums"]["usage_kind"]
          qty: number
          unit_cost: number
          signed_qty?: never
          cost?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          date?: string
          batch_id?: number
          item_id?: number
          kind?: Database["public"]["Enums"]["usage_kind"]
          qty?: number
          unit_cost?: number
          signed_qty?: never
          cost?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "usages_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "usages_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      weights: {
        Row: {
          id: number
          date: string
          batch_id: number
          sample_size: number
          total_weight_kg: number
          avg_weight_g: number | null
          is_void: boolean
          note: string | null
          created_at: string
        }
        Insert: {
          id?: never
          date: string
          batch_id: number
          sample_size: number
          total_weight_kg: number
          avg_weight_g?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: never
          date?: string
          batch_id?: number
          sample_size?: number
          total_weight_kg?: number
          avg_weight_g?: never
          is_void?: boolean
          note?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "weights_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "batches"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      v_batch_summary: {
        Row: {
          id: number | null
          code: string | null
          status: string | null
          start_date: string | null
          close_date: string | null
          note: string | null
          age_days: number | null
          chicks_placed: number | null
          dead: number | null
          mortality_pct: number | null
          birds_sold: number | null
          live_balance: number | null
          net_kg_sold: number | null
          avg_sale_weight_kg: number | null
          latest_avg_weight_g: number | null
          latest_weight_date: string | null
          feed_bags: number | null
          feed_kg: number | null
          fcr: number | null
          fcr_estimated: number | null
          chick_cost: number | null
          feed_cost: number | null
          medicine_cost: number | null
          vaccine_cost: number | null
          husk_cost: number | null
          total_cost: number | null
          sales_amount: number | null
          gross_margin: number | null
          cost_per_kg: number | null
          margin_per_chick: number | null
          received: number | null
          sales_due: number | null
          last_usage_date: string | null
        }
        Relationships: []
      }
      v_batch_weights: {
        Row: {
          id: number | null
          batch_id: number | null
          date: string | null
          age_days: number | null
          age_week: number | null
          sample_size: number | null
          total_weight_kg: number | null
          avg_weight_g: number | null
          gain_g: number | null
          note: string | null
        }
        Relationships: []
      }
      v_bills: {
        Row: {
          bill_type: string | null
          bill_id: number | null
          date: string | null
          party: Database["public"]["Enums"]["party_type"] | null
          party_id: number | null
          batch_id: number | null
          description: string | null
          amount: number | null
          paid: number | null
          due: number | null
          payment_status: string | null
          last_payment_date: string | null
        }
        Relationships: []
      }
      v_buyer_balance: {
        Row: {
          id: number | null
          code: string | null
          name: string | null
          company: string | null
          phone: string | null
          is_active: boolean | null
          bills: number | null
          billed: number | null
          received: number | null
          due: number | null
        }
        Relationships: []
      }
      v_data_checks: {
        Row: {
          check_name: string | null
          ref_table: string | null
          ref_id: number | null
          ref_code: string | null
          detail: string | null
        }
        Relationships: []
      }
      v_item_stock: {
        Row: {
          id: number | null
          code: string | null
          name: string | null
          category: Database["public"]["Enums"]["item_category"] | null
          unit: string | null
          is_active: boolean | null
          purchased_qty: number | null
          issued_qty: number | null
          returned_qty: number | null
          balance_qty: number | null
          avg_unit_cost: number | null
          stock_value: number | null
        }
        Relationships: []
      }
      v_reminders: {
        Row: {
          kind: string | null
          batch_id: number | null
          batch_code: string | null
          message: string | null
        }
        Relationships: []
      }
      v_supplier_balance: {
        Row: {
          id: number | null
          code: string | null
          name: string | null
          company: string | null
          phone: string | null
          is_active: boolean | null
          bills: number | null
          billed: number | null
          paid: number | null
          due: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      create_chick_purchase: {
        Args: {
          p_date: string
          p_batch_id: number
          p_supplier_id: number
          p_chicks_placed: number
          p_rate: number
          p_discount?: number
          p_paid?: number
          p_method?: Database["public"]["Enums"]["payment_method"]
          p_note?: string
        }
        Returns: number
      }
      create_purchase: {
        Args: {
          p_date: string
          p_item_id: number
          p_supplier_id: number
          p_qty: number
          p_unit_price: number
          p_paid?: number
          p_method?: Database["public"]["Enums"]["payment_method"]
          p_note?: string
        }
        Returns: number
      }
      create_sale: {
        Args: {
          p_date: string
          p_batch_id: number
          p_buyer_id: number
          p_male_count: number
          p_female_count: number
          p_grade: Database["public"]["Enums"]["sale_grade"]
          p_gross_weight_kg: number
          p_deduction_per_crate_g: number
          p_rate: number
          p_discount?: number
          p_received?: number
          p_method?: Database["public"]["Enums"]["payment_method"]
          p_note?: string
        }
        Returns: number
      }
    }
    Enums: {
      item_category: "FEED" | "MEDICINE" | "VACCINE" | "HUSK"
      mortality_reason: "NORMAL" | "ACCIDENT" | "ILLNESS"
      party_type: "SUPPLIER" | "BUYER"
      payment_method: "CASH" | "BANK" | "MOBILE"
      sale_grade: "A" | "B" | "C"
      shed_type: "BROODER" | "GROWER"
      usage_kind: "ISSUE" | "RETURN"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database["public"]
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]
